language: node_js
node_js:
  - "8"
dist: trusty
sudo: false
branches:
  only:
    - master
before_install:
  - mkdir $HOME/.now
  - echo "{\"token\":\"$NOW_TOKEN\"}" > $HOME/.now/auth.json
install:
  - "yarn --prefer-offline"
cache:
  directories:
    - .yarn-local-mirror
email:
  on_failure: change
  on_success: never
deploy:
  provider: npm
  email:
    secure: "o7GfRNIWkzKpx6gyM7THL7Bn92gQfkrvR4siOHFboOU8SnQ/4bWt5oFaFcf5q9k0t/ZM7vmP5BGCtlPTLrRJ+RhCYdkaVQDql/wZxicWw2QC3owPngrETuLlXukRDYMYBcBU7jbN4FO3ASGo089Qc/vhgmySqeC57RNu8hN77iWnjjl6CG856BahqO9TsT6T7K6q0SAnnTORX/DgNbpEeYx3CN/wQcWG7YtUdkHZl9oz5SDzOec4GQSclUD9mM5aF7hPGEj8vetpmXBXsTq0IxnsfEkCnsOydkypBbi/h4MPbnbyppsluZUmKLofGe7ab02Ec/I1CMuUnXsi2NxgP4BriTDdnCWFMBL9uv4JbvkKmPp5rt2RL8GcCGNofuJAEB5biUizA8zvkb+4vW2cEz51UsXXoynpOKqz3CSszmkycV14W5ag70b6xgOuQNX8ZWJQc4NXqUUzyq1+/63sHfNtXDU8SqhOyNt+9QlbWJ99Kcli0SCsOmkoVksJLThpFrEcUfe9pGO3vtMWPdOxMammKw7ZsAiQnhUQL1DdKiyYbxSpB7zq/iIHrzk4acw7mW/kNGugpAG55R1BqYr9KCFmUS+HMPpDlnEbTnc5dyXjWaySYqoEk2DD8Zi2ebxUCfHO6Jtxj38afgHDq/8ALAG2EUdR6JnTeUDcA7J5BsA="
  api_key:
    secure: "TE0uez+1E3q2RNlyqLJvdt3N5xR9FkElk4gMvKnDzPltxYcwMcKQ2m7XcOczYHV9gdcNxDTI/V7gymfkV35GNP5KFE0AZW9YdvIAxeAxTFoAg54j4b4wN6bTxfFGwVXPXBpUm7+GyPB9HJS2pI48m4gUpI4bcFsMwtY8CBGJlIOfOi9K2arjH0hbdalRFzmilwZnmDb8yTjkxrX0MbWXQ1NwH0yKDiU7NDLppSkJ2kWaaWDJZQv5xIYjFv7rdLOnXzv0B+iB3vm2tKxZN1eLlKSblqvCXe+EMf7i+sw7awalmBJjdjz6iK4EqQoyGSGgWHIgEzb5c6EzDjO7/XLMctTYfC/tHxUR7ti+4/gvR4CRA4IG/mC8D5HxwBD+/sjVB9IRlocCKAbPehOp0wWORNr5ra4fXcix0jBp5y12+WHT1jn3ZsPRv538dwhgAu221hw+YJE/2h0il3NGElalceXIbX25+0lkO7QRcPTwOZ+kEejQ9syrutfg7dEPHeHMfq9k/x+FbxzeICzojVYdE0TMJADGbl6X+Pd8ZpqDVJT4gTAs7sFJ/kXlIJos2bu2GhhEyEAawxfF7Cp86SsIJIojUhbzIiTn81PePmimn9OUfdqsHmTwlf4fsdevQYPLRJrctiqvRvMtfVFQa47NuJFbkh3I+z87qlm2CoePKFw="
  on:
    branch: master
repo: pckilgore/now-builder-s3
