language: node_js
node_js:
  - "8"
dist: trusty
sudo: false
branches:
  only:
    - master
before_install:
  - mkdir $HOME/.now
  - echo "{\"token\":\"$NOW_TOKEN\"}" > $HOME/.now/auth.json
install:
  - "yarn --prefer-offline"
cache:
  directories:
    - .yarn-local-mirror
email:
  on_failure: change
  on_success: never
deploy:
  provider: npm
  email:
    secure: "o7GfRNIWkzKpx6gyM7THL7Bn92gQfkrvR4siOHFboOU8SnQ/4bWt5oFaFcf5q9k0t/ZM7vmP5BGCtlPTLrRJ+RhCYdkaVQDql/wZxicWw2QC3owPngrETuLlXukRDYMYBcBU7jbN4FO3ASGo089Qc/vhgmySqeC57RNu8hN77iWnjjl6CG856BahqO9TsT6T7K6q0SAnnTORX/DgNbpEeYx3CN/wQcWG7YtUdkHZl9oz5SDzOec4GQSclUD9mM5aF7hPGEj8vetpmXBXsTq0IxnsfEkCnsOydkypBbi/h4MPbnbyppsluZUmKLofGe7ab02Ec/I1CMuUnXsi2NxgP4BriTDdnCWFMBL9uv4JbvkKmPp5rt2RL8GcCGNofuJAEB5biUizA8zvkb+4vW2cEz51UsXXoynpOKqz3CSszmkycV14W5ag70b6xgOuQNX8ZWJQc4NXqUUzyq1+/63sHfNtXDU8SqhOyNt+9QlbWJ99Kcli0SCsOmkoVksJLThpFrEcUfe9pGO3vtMWPdOxMammKw7ZsAiQnhUQL1DdKiyYbxSpB7zq/iIHrzk4acw7mW/kNGugpAG55R1BqYr9KCFmUS+HMPpDlnEbTnc5dyXjWaySYqoEk2DD8Zi2ebxUCfHO6Jtxj38afgHDq/8ALAG2EUdR6JnTeUDcA7J5BsA="
  api_key:
    secure: "l6rAQxLIdbEg4NNg6NGCxlDBivbnH4j2H4zpGZcboqN/A677NpFB9jVxoSHHrr9n4CqRZlgixEjc5ukmtmyy6Suz3G2pG9go5hXI6vC6kx29FTNLnMrCf/h+XDBWQW2PzOY4nYGx5sLTRtnNNy9z/SNCKiBNcH/o0dVy/uTRKq6gq76kUHjl9PfILEf8rKRMdf6YBu1iJnPrUmjq4AUWiNk8qTKxUoGiI7V0GzVptr2suJ1zJ/XDH9XmnFzmfwcHW8N19Kci9O1pqGiffOoaocZAejkY3qlwj3Pfx7SmVFM1u1uJVGcL/9ZbGWO04hPZVIuTy0m2UX6ebeJueIu/uBxqIVZDXpDcm00I5iJhPRjJyuHPjpX7J5odWK+ezR9i+LCNedy+IMF9cgYf4Tc0Z99V7uHEoRiXkGyBkymQkI8Pm4BihJY8jTcFeZDi5JmtZJ9RF4RmAOOkgzdd4WBiI2q75vevt+BQDFdQlGTk2shfukhb1x2GWyVfFpuFBH8er1Sc8pkuJScdgs0RtvxX+zHGxXTRxoLiVBzNju8W0/4pkvX3Hzk6TP8e+CAj0Yf2RCJDJrSHddjwn0a3ztYqjWAmrvXwfeWnxRHpqx5BHh1O0+3ymJs63cdx9un/NLbVotif7597kQSay0qrUuKNmroKezyeln9dYDdNgKhyd94="
  on:
    branch: master
repo: pckilgore/now-builder-s3
